"""Added version, date and software version columns

Revision ID: 77642de1867a
Revises: d0457f3e98c8
Create Date: 2024-08-07 13:03:30.889623

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "77642de1867a"
down_revision = "d0457f3e98c8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("version", sa.Integer(), nullable=False))
    op.add_column("files", sa.Column("date", sa.DateTime(), nullable=False))
    op.add_column(
        "files", sa.Column("software_version", sa.String(length=16), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "software_version")
    op.drop_column("files", "date")
    op.drop_column("files", "version")
    # ### end Alembic commands ###
