"""Added version, hash, date and software version columns

Revision ID: 669111c45c37
Revises: d0457f3e98c8
Create Date: 2024-08-09 13:35:21.578940

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "669111c45c37"
down_revision = "d0457f3e98c8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("version", sa.Integer(), nullable=False))
    op.add_column("files", sa.Column("hash", sa.String(length=64), nullable=False))
    op.add_column("files", sa.Column("date", sa.DateTime(), nullable=False))
    op.add_column(
        "files", sa.Column("software_version", sa.String(length=16), nullable=False)
    )
    op.create_unique_constraint(None, "files", ["path"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "files", type_="unique")
    op.drop_column("files", "software_version")
    op.drop_column("files", "date")
    op.drop_column("files", "hash")
    op.drop_column("files", "version")
    # ### end Alembic commands ###
